print(">> Running Setup in Arangosh\n");

const users = require('@arangodb/users');

print("Create user: ", process.env.ARANGO_DB_USER);
if (users.save(process.env.ARANGO_DB_USER, process.env.ARANGO_DB_USER_PASSWORD)) {
  print("User created successfully\n");
}

print("Create database: ", process.env.ARANGO_DB_NAME);
if (db._createDatabase(process.env.ARANGO_DB_NAME)) {
  print("Database created successfully\n");
}
users.grantDatabase(process.env.ARANGO_DB_USER, process.env.ARANGO_DB_NAME, 'rw');

db._useDatabase(process.env.ARANGO_DB_NAME);

// Optionally load dummy data generated by app test
let testDataFlag = false;
if (process.env.ARANGO_DB_RUN_WITH_TEST_DATA == 'yes') {
  testDataFlag = true;
  print("Loading test data\n");
}
else {
  testDataFlag = false;
  print("Loading empty collections\n");
}

const testData = require(process.env.ARANGODB_DESTINATION_CONTAINER_DOCKER_SHARED_VOLUME_SCRIPTS_PATH + '/test-data/testData.json');

print(typeof testData.resources);

// const collectionNames = Object.keys(testData);
print('Document Collections')
for (collectionName in testData.resources) {
  print(`Attempting to add collection "${collectionName}" to ${process.env.ARANGO_DB_NAME}`);
  // TODO: need to pass in collection type document or edge
  if (db._create(collectionName)) {
    print(`Created Collection ${collectionName}`);
    if (testDataFlag) {
      print(`Attempting to add data to collection "${collectionName}"`);
      const data = testData.resources[collectionName];
      data.forEach(document => {
        if (db._collection(collectionName).save(document)) {
          print(`Added document to Collection ${collectionName}`);
        }
        else {
          print(`Document could not be added to "${collectionName}"`);
        }
      });
    }
  }
  else {
    print(`Collection "${collectionName}" could not be created`);
  }
}

print('Edge Collections')
const edgeCollectionName = 'resource_edge_connections';
print(`Attempting to add collection "${edgeCollectionName}" to ${process.env.ARANGO_DB_NAME}`);
// TODO: need to pass in collection type document or edge
if (db._createEdgeCollection(edgeCollectionName)) {
  print(`Created Edge Collection ${edgeCollectionName}`);
  if (testDataFlag) {
     testData.resource_edge_connections.forEach(edge => {
        print(`Attempting to add data to collection "${edgeCollectionName}"`);
        if (db._collection(edgeCollectionName).save(edge)) {
          print(`Added document to Collection ${edgeCollectionName}`);
        }
        else {
          print(`Document could not be added to "${edgeCollectionName}"`);
        }
      });
  }
}
else {
  print(`Collection "${edgeCollectionName}" could not be created`);
}
