print(">> Running Setup in Arangosh\n");

const users = require('@arangodb/users');

print("Create user: ", process.env.ARANGO_DB_USER);
if (users.save(process.env.ARANGO_DB_USER, process.env.ARANGO_DB_USER_PASSWORD)) {
  print("User created successfully\n");
}

print("Create database: ", process.env.ARANGO_DB_NAME);
if (db._createDatabase(process.env.ARANGO_DB_NAME)) {
  print("Database created successfully\n");
}
users.grantDatabase(process.env.ARANGO_DB_USER, process.env.ARANGO_DB_NAME, 'rw');

db._useDatabase(process.env.ARANGO_DB_NAME);

// Optionally load dummy data generated by app test
let testDataFlag = false;
if (process.env.ARANGO_DB_RUN_WITH_TEST_DATA == 'yes') {
  testDataFlag = true;
  print("Loading test data\n");
}
else {
  testDataFlag = false;
  print("Loading empty collections\n");
}

const testData = require(process.env.ARANGODB_DESTINATION_CONTAINER_DOCKER_SHARED_VOLUME_SCRIPTS_PATH + '/test-data/testData.json');

for (collectionType in testData) {
  for (collectionName in testData[collectionType]) {
    addCollectionAndData(collectionName, collectionType, testData[collectionType][collectionName]);
  }
}

function addCollectionAndData(collectionName, collectionType, data) {
  print(`Attempting to add ${collectionType} collection "${collectionName}" to ${process.env.ARANGO_DB_NAME}`);
  let success = false;
  if (collectionType == 'document') {
    if (db._create(collectionName)) {
      success = true;
    }
  }
  else if (collectionType == 'edge') {
    if (db._createEdgeCollection(collectionName)) {
      success = true;
    }
  }

  if (success) {
    if (testDataFlag) {
      print(`Attempting to add data to collection "${collectionName}"`);
      data.forEach(document => {
        if (db._collection(collectionName).save(document)) {
          print(`Added document to Collection ${collectionName}`);
        }
        else {
          print(`Document could not be added to "${collectionName}"`);
        }
      });
    }
  }
}
